//
// Copyright (c) 2025-2026 v0lt, Aleksoid
//
// SPDX-License-Identifier: MIT
//

#pragma once

#ifndef FCC
#define FCC(ch4) ((((DWORD)(ch4) & 0xFF) << 24) |     \
                  (((DWORD)(ch4) & 0xFF00) << 8) |    \
                  (((DWORD)(ch4) & 0xFF0000) >> 8) |  \
                  (((DWORD)(ch4) & 0xFF000000) >> 24))
#endif

#ifndef DEFINE_MEDIATYPE_GUID
#define DEFINE_MEDIATYPE_GUID(name, format) \
    DEFINE_GUID(name,                       \
    format, 0x0000, 0x0010, 0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71);
#endif

// Media subtypes
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_Y800,      FCC('Y800'));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_YV16,      FCC('YV16'));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_NV16,      FCC('NV16'));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_YV24,      FCC('YV24'));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_I420,      FCC('I420')); // from "wmcodecdsp.h"
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_Y42B,      FCC('Y42B'));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_444P,      FCC('444P'));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_Y210,      FCC('Y210'));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_Y216,      FCC('Y216'));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_v210,      FCC('v210'));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_Y410,      FCC('Y410'));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_Y416,      FCC('Y416'));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_b48r,      FCC('b48r'));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_b64a,      FCC('b64a'));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_r210,      FCC('r210'));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_Y8,        MAKEFOURCC('Y','8',0x20,0x20)); // 'Y8  '
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_Y16,       MAKEFOURCC('Y','1',0,16));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_YUV444P16, MAKEFOURCC('Y','3',0,16));
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_RGB48,     MAKEFOURCC('R','G','B',48)); // 'RGB0'
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_BGR48,     MAKEFOURCC('B','G','R',48)); // 'BGR0'
DEFINE_MEDIATYPE_GUID(MEDIASUBTYPE_BGRA64,    MAKEFOURCC('B','R','A',64)); // 'BRA@'

DEFINE_GUID(MEDIASUBTYPE_LAV_RAWVIDEO, 0xd80fa03c, 0x35c1, 0x4fa1, 0x8c, 0x8e, 0x37, 0x5c, 0x86, 0x67, 0x16, 0x6e);

// non-standard values for Transfer Matrix
#define VIDEOTRANSFERMATRIX_FCC     6
#define VIDEOTRANSFERMATRIX_YCgCo   7