//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MpcVideoRenderer.rc
//
#define IDD_MAINPROPPAGE                102
#define IDD_INFOPROPPAGE                103
#define IDS_MAINPROPPAGE_TITLE          104
#define IDS_INFOPROPPAGE_TITLE          105
#define IDF_SHADER_RESIZER_MITCHELL4_X  712
#define IDF_SHADER_RESIZER_MITCHELL4_Y  713
#define IDF_SHADER_RESIZER_CATMULL4_X   714
#define IDF_SHADER_RESIZER_CATMULL4_Y   715
#define IDF_SHADER_RESIZER_LANCZOS2_X   722
#define IDF_SHADER_RESIZER_LANCZOS2_Y   723
#define IDF_SHADER_RESIZER_LANCZOS3_X   724
#define IDF_SHADER_RESIZER_LANCZOS3_Y   725
#define IDF_SHADER_DOWNSCALER_BOX_X     730
#define IDF_SHADER_DOWNSCALER_BOX_Y     731
#define IDF_SHADER_DOWNSCALER_BILINEAR_X 732
#define IDF_SHADER_DOWNSCALER_BILINEAR_Y 733
#define IDF_SHADER_DOWNSCALER_HAMMING_X 734
#define IDF_SHADER_DOWNSCALER_HAMMING_Y 735
#define IDF_SHADER_DOWNSCALER_BICUBIC_X 736
#define IDF_SHADER_DOWNSCALER_BICUBIC_Y 737
#define IDF_SHADER_DOWNSCALER_LANCZOS_X 738
#define IDF_SHADER_DOWNSCALER_LANCZOS_Y 739
#define IDF_SHADER_CONVERT_COLOR        750
#define IDF_SHADER_CONVERT_COLOR_ST2084 751
#define IDF_SHADER_CONVERT_COLOR_HLG    752
#define IDF_SHADER_CORRECTION_ST2084    753
#define IDF_SHADER_CORRECTION_HLG       754
#define IDF_SHADER_CORRECTION_YCGCO     755
#define IDF_VSH11_SIMPLE                800
#define IDF_PSH11_SIMPLE                801
#define IDF_PSH11_CONVERT_COLOR         802
#define IDF_PSH11_CONVERT_COLOR_ST2084  803
#define IDF_PSH11_CONVERT_COLOR_HLG     804
#define IDF_PSH11_CORRECTION_ST2084     805
#define IDF_PSH11_CORRECTION_HLG        806
#define IDF_PSH11_CORRECTION_YCGCO      807
#define IDF_PSH11_RESIZER_MITCHELL4_X   810
#define IDF_PSH11_RESIZER_MITCHELL4_Y   811
#define IDF_PSH11_RESIZER_CATMULL4_X    812
#define IDF_PSH11_RESIZER_CATMULL4_Y    813
#define IDF_PSH11_RESIZER_LANCZOS2_X    814
#define IDF_PSH11_RESIZER_LANCZOS2_Y    815
#define IDF_PSH11_RESIZER_LANCZOS3_X    816
#define IDF_PSH11_RESIZER_LANCZOS3_Y    817
#define IDF_PSH11_DOWNSCALER_BOX_X      820
#define IDF_PSH11_DOWNSCALER_BOX_Y      821
#define IDF_PSH11_DOWNSCALER_BILINEAR_X 822
#define IDF_PSH11_DOWNSCALER_BILINEAR_Y 823
#define IDF_PSH11_DOWNSCALER_HAMMING_X  824
#define IDF_PSH11_DOWNSCALER_HAMMING_Y  825
#define IDF_PSH11_DOWNSCALER_BICUBIC_X  826
#define IDF_PSH11_DOWNSCALER_BICUBIC_Y  827
#define IDF_PSH11_DOWNSCALER_LANCZOS_X  828
#define IDF_PSH11_DOWNSCALER_LANCZOS_Y  829
#define IDC_STATIC1                     1001
#define IDC_CHECK1                      1002
#define IDC_CHECK2                      1003
#define IDC_CHECK3                      1004
#define IDC_CHECK4                      1005
#define IDC_CHECK5                      1006
#define IDC_CHECK6                      1007
#define IDC_COMBO1                      1008
#define IDC_COMBO2                      1009
#define IDC_COMBO3                      1010
#define IDC_COMBO4                      1011
#define IDC_EDIT1                       1012
#define IDC_EDIT2                       1013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
